### ISSUE TITLE
TPM integration onto Liquid Router

### ISSUE THREAD

**Issue by metinburak** [subutai-io/liquid-router#1]
The TPM IC integration onto the LR will be handled in analysis and implementation stage.
Hint: There are 2 possibilities : 
1- TPM as an add on module for LR 1.0 using the eMMC extension connectors
2- Design update of LR 1.0 using the TPM having the footprint on the PCB.

**Comment by akarasulu** [comment]
Just to put this on the record with this issue. The use of Trustzone to implement TPM functionality is not feasible. We should use a formal TPM 2.0 IC.

**Comment by metinburak** [comment]
acknowledge @akarasulu

**Comment by metinburak** [comment]
we have a TPM interface now as an add-on module with interface of iic.
