### ISSUE TITLE
Test GPIO pins between Parallella and Artix

### ISSUE THREAD

**Issue by bkukanov** [subutai-io/liquid-router#11]
We have to verify the boards communications between Parallella and Artix through GPIO pins

**Comment by bkukanov** [comment]
We have found that has short cut on LR between pos and neg GPIO 0 pins of PEC connector. We have tested other boards, but it exist just in one board and seems soldering problem

**Comment by bkukanov** [comment]
We have tried to resolder PEC connectors pins number 3 & 5, but it didn't help. Now this board is blocked with short cut

**Comment by akarasulu** [comment]
@bkukanov why don't you send that back. I'll give you mine after some modifications from @metinburak. Please inform @metinburak to get it from me ASAP and also send yours back here ASAP.

**Comment by bkukanov** [comment]
@akarasulu I supposed you also need LR

**Comment by bkukanov** [comment]
New LR has been arrived and GPIO pins between Parallella and Artix worked fine
