### ISSUE TITLE
Adaptation of HC "clock divide" module to provide rated high speed clock

### ISSUE THREAD

**Issue by AzamatBeksadaev** [subutai-io/liquid-router#15]
**Introduction:**

Host Controller (HC) works in two clock domains _AXI_ and _SD_. _AXI_ clock supplies total _HC synchronisation_. _SD domain_ supplies eMMC card. It derivatives from _AXI clock_ signal. _SD_ clock produced by dividing _AXI clock_ on certain "divisor value" comes from Host Driver (HD). eMMC standard has five timing modes: 
- Card Identification (400KHz)
- Normal speed (25MHz)
- High speed (50MHz)
- HS200 (200MHz)
- HS400 (400MHz)

_SD domain_ jumps to clock value depends on what mode is on. In order to transfer data through Serializer/Deserializer (SERDES) we need to provide rated high speed clock based on _SD clock_ regardless in what timing mode is _SD domain_.
notice:  Last two modes are not supported by current version of controller. 

**Implementaion:**
"Clock dividing" module in HC need to be modified to produce new output rated clock to supply SERDES ip core with high speed clock.

**Comment by AzamatBeksadaev** [comment]
CLC_DIV module consists of the almost the same blocks where clock is divided respectively. Amount of blocks depend on how many clock signals need to produce. Block below is that one.
```
always @ (posedge AXI_CLOCK or posedge AXI_RST)
begin
 if (AXI_RST == 0) begin
   clk_div1 <= 12'h000;
   SD_CLK_1  <= 1;
 end
 else if (clk_div1 == divisor1) begin
   clk_div1 <= 0;
   SD_CLK_1 <= ~SD_CLK_1;
 end 
 else begin
   clk_div1  <= clk_div1 + 1;
   SD_CLK_1 <=  SD_CLK_1;
 end
end
```
Let's say input frequency is 200 MHz or 5 ns, results of output freq in table:

Divisor (K) |T_output, ns|F_output, MHz|
|:---:|:---:|:---:|
8'h00|10|100|
8'h01|20|50|
8'h02|30|33.3|
8'h03|40|25|
8'h04|50|20|
8'h05|60|16.6|
...|...|...|

Thus, the period of T_output equals to:
![f3](https://cloud.githubusercontent.com/assets/10692937/23339951/0a261b64-fc57-11e6-8875-f723e3bb926c.png)
Where _K_ is Divisor.

**Comment by Bekzade** [comment]
Commit 6b6da43fec16e993abfbd7039d765fd896bf96b3

**Comment by AzamatBeksadaev** [comment]
Commit 6b6da43fec16e993abfbd7039d765fd896bf96b3
