### ISSUE TITLE
Basic signal transfer between Zynq PL and Artix on LR.

### ISSUE THREAD

**Issue by metinburak** [subutai-io/liquid-router#9]
We should send a signal from PL of Zynq using Linux uio interface or whatever suits, then we should read the signal from Artix 7 on LR and forward it to either emmc connector and observe by scope, or send it to another pin of Zynq PL and read it from Linux or whatever suits this application. With this test, we will be ready for LVDS applications.

**Comment by AzamatBeksadaev** [comment]
Tests with loopback signals passed. 5 input wires was connected in 5 output wires in the Artix7 FPGA. From Zynq PL we sent data to output 5 wire bus which is connected to input wires of Artix and received the same data from input wires in Zynq PL.

**Comment by AzamatBeksadaev** [comment]
Block Design of test project in Zynq PL:
![bdzynqplissue9](https://cloud.githubusercontent.com/assets/10692937/22135661/d43f2d08-def9-11e6-80d5-27c169f9bdab.png)

Block Design of test project in Artix FPGA
![screenshot from 2017-01-20 10 08 16](https://cloud.githubusercontent.com/assets/10692937/22135631/97eba11a-def9-11e6-96bd-3431e96b28a8.png)

Waveform captured from Hardware Manager shows output and input wires. There is delay for 1 clock cycle  between output and input signals.
![waveformissue9](https://cloud.githubusercontent.com/assets/10692937/22135735/4b981aae-defa-11e6-9c55-cc4ec7538920.png)

This signal loop can be checked by SW also. The **_axi_gpio_** IP core allows read status of input signal from `base_addr+8` offset address:
```
root@linaro-developer:/home/linaro/gpio_dev_mem# ./gpio-dev-mem-test -g 0x43c00000 -o 0
GPIO access through /dev/mem.
root@linaro-developer:/home/linaro/gpio_dev_mem# ./gpio-dev-mem-test -g 0x43c00000 -o 31
GPIO access through /dev/mem.
root@linaro-developer:/home/linaro/gpio_dev_mem# ./gpio-dev-mem-test -g 0x43c00008 -i
GPIO access through /dev/mem.
gpio dev-mem test: input: 0000001f
root@linaro-developer:/home/linaro/gpio_dev_mem# ./gpio-dev-mem-test -g 0x43c00000 -o 1
GPIO access through /dev/mem.
root@linaro-developer:/home/linaro/gpio_dev_mem# ./gpio-dev-mem-test -g 0x43c00008 -i
GPIO access through /dev/mem.
gpio dev-mem test: input: 00000001
root@linaro-developer:/home/linaro/gpio_dev_mem# 
```
